name: Shellcheck
on:
  push:
    paths:
      - '**/*.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@1.0.0
      with:
        check_together: 'yes'
